name: Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  slack-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Slack-Benachrichtigung senden
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚀 *Staging-Pipeline gestartet!* \nBenutzer: ${{ github.actor }}\nWorkflow: ${{ github.workflow }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}